feat: add some tests for the app
additions for the ci/cd of the application and automation

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -35,6 +35,38 @@ jobs:
       
     - name: Build project
       run: dotnet build ./environmentalAgencyApp/EAA/EAA.csproj --configuration Release
+
+    - name: Restore test dependencies
+      run: dotnet restore ./environmentalAgencyApp/Tests/Tests.csproj
       
-    - name: Test
-      run: dotnet test ./environmentalAgencyApp/EAA.sln
+    - name: Run tests
+      run: dotnet test ./environmentalAgencyApp/Tests/Tests.csproj --configuration Release --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"
+      
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Test Results
+        path: 'environmentalAgencyApp/Tests/TestResults/*.trx'
+        reporter: dotnet-trx
+        fail-on-error: false
+        
+    - name: Code Coverage Report
+      uses: irongut/CodeCoverageSummary@v1.3.0
+      with:
+        filename: 'environmentalAgencyApp/Tests/TestResults/**/coverage.cobertura.xml'
+        badge: true
+        fail_below_min: false
+        format: markdown
+        hide_branch_rate: false
+        hide_complexity: false
+        indicators: true
+        output: both
+        thresholds: '60 80'
+        
+    - name: Add Coverage PR Comment
+      uses: marocchino/sticky-pull-request-comment@v2
+      if: github.event_name == 'pull_request'
+      with:
+        recreate: true
+        path: code-coverage-results.md
